#!/bin/bash

# Simple PWA Icon Generator for macOS
# Uses the existing PNG logo as base and resizes with sips

RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}🎨 PWA Icon Generator (Simple)${NC}"
echo "======================================"

# Check if we have a source PNG file (the one generated by qlmanage)
SOURCE_PNG="public/icons/mediad-logo.svg.png"
if [ ! -f "$SOURCE_PNG" ]; then
    echo -e "${RED}❌ Source PNG not found: $SOURCE_PNG${NC}"
    echo -e "${YELLOW}💡 Run the main script first to generate the base PNG${NC}"
    exit 1
fi

# Create icons directory
ICONS_DIR="public/icons"
mkdir -p "$ICONS_DIR"

echo -e "${GREEN}📁 Using source image: $SOURCE_PNG${NC}"
echo -e "${BLUE}🔄 Generating all icon sizes...${NC}"

# Define required sizes
declare -a SIZES=(
    "16:favicon-16x16.png"
    "32:favicon-32x32.png" 
    "48:icon-48x48.png"
    "72:icon-72x72.png"
    "96:icon-96x96.png"
    "128:icon-128x128.png"
    "144:icon-144x144.png"
    "152:icon-152x152.png"
    "167:icon-167x167.png"
    "180:apple-touch-icon.png"
    "192:icon-192x192.png"
    "256:icon-256x256.png"
    "384:icon-384x384.png"
    "512:icon-512x512.png"
    "1024:icon-1024x1024.png"
)

# Generate each size using sips
for size_info in "${SIZES[@]}"; do
    IFS=':' read -ra PARTS <<< "$size_info"
    SIZE="${PARTS[0]}"
    FILENAME="${PARTS[1]}"
    
    echo -e "  📐 Generating ${SIZE}x${SIZE} → $FILENAME"
    
    # Use sips to resize the PNG
    if sips -z "$SIZE" "$SIZE" "$SOURCE_PNG" --out "$ICONS_DIR/$FILENAME" > /dev/null 2>&1; then
        echo -e "    ${GREEN}✅ $FILENAME${NC}"
    else
        echo -e "    ${RED}❌ Failed to generate $FILENAME${NC}"
    fi
done

# Create maskable version
echo -e "${BLUE}🎭 Creating maskable icon...${NC}"
if [ -f "$ICONS_DIR/icon-512x512.png" ]; then
    cp "$ICONS_DIR/icon-512x512.png" "$ICONS_DIR/icon-512x512-maskable.png"
    echo -e "${GREEN}✅ Maskable icon created${NC}"
fi

# Create favicon.ico by copying the 32x32 version
echo -e "${BLUE}🌐 Creating favicon.ico...${NC}"
if [ -f "$ICONS_DIR/favicon-32x32.png" ]; then
    cp "$ICONS_DIR/favicon-32x32.png" "public/favicon.ico"
    echo -e "${GREEN}✅ favicon.ico created (as PNG)${NC}"
fi

# List all generated files
echo -e "${BLUE}📋 Generated files:${NC}"
find "$ICONS_DIR" -name "*.png" -exec basename {} \; | sort | while read file; do
    echo -e "  📄 $file"
done

echo ""
echo -e "${GREEN}🎉 Icon generation complete!${NC}"
echo -e "${YELLOW}💡 All PWA icon sizes generated successfully!${NC}"
echo ""